# Generated by Django 3.1.6 on 2021-03-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=60)),
                ('userImage', models.ImageField(upload_to='userImages')),
                ('fullName', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('token', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
