# Generated by Django 3.1.6 on 2021-03-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketId', models.CharField(max_length=60)),
                ('ticketDate', models.DateTimeField()),
                ('ticketInfo', models.CharField(max_length=2000)),
                ('userId', models.CharField(blank=True, max_length=20, null=True)),
                ('assigned', models.BooleanField(default=False)),
            ],
        ),
    ]
