# Generated by Django 3.1.6 on 2021-03-02 11:48

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mail_message', models.CharField(max_length=30)),
                ('ticket_id', models.CharField(max_length=60)),
            ],
        ),
        migrations.RenameField(
            model_name='ticketmodel',
            old_name='userId',
            new_name='agent',
        ),
        migrations.RemoveField(
            model_name='ticketmodel',
            name='ticketDate',
        ),
        migrations.RemoveField(
            model_name='ticketmodel',
            name='ticketInfo',
        ),
        migrations.AddField(
            model_name='ticketmodel',
            name='approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 3, 2, 11, 47, 29, 660869, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketmodel',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 3, 2, 11, 47, 41, 5628, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketmodel',
            name='latitude',
            field=models.CharField(default=datetime.datetime(2021, 3, 2, 11, 47, 55, 808249, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketmodel',
            name='longitude',
            field=models.CharField(default=datetime.datetime(2021, 3, 2, 11, 48, 6, 738587, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketmodel',
            name='name_of_location',
            field=models.CharField(default=datetime.datetime(2021, 3, 2, 11, 48, 28, 440553, tzinfo=utc), max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketmodel',
            name='priority',
            field=models.CharField(default=datetime.datetime(2021, 3, 2, 11, 48, 39, 689356, tzinfo=utc), max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketmodel',
            name='ticketype',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
